/*
 * Web debugging proxy server.
 * Generated by Hoxy.
 * http://greim.github.io/hoxy/
 * https://github.com/greim/hoxy
 * Copyright (c) <year> by First Last <email>
 * See "license.txt" for more info.
 */

var hoxy = require('hoxy');
var parseArgs = require('minimist');
var _ = require('lodash_node');
var hoxyConfig = require('./hoxy.json');

// CLI args override hoxy.json properties
var cliArgs = parseArgs(process.argv.slice(2));
var args = _.extend(hoxyConfig, {
  port: parseInt(cliArgs.port),
  upstreamProxy: cliArgs['upstream-proxy'],
  reverse: cliArgs.reverse
});

// CLI args turn off hoxy.json args by setting to "none"
_.forIn(args, function(val, key){
  if (val === 'none'){
    delete args[key];
  }
});

// create a proxy server
var proxy = new hoxy.Proxy(args);
proxy.log('error warn', process.stderr);
proxy.log('info', process.stdout);
proxy.listen(args.port);

// intercept requests
proxy.intercept({
  phase: 'request'
}, function(req, resp) {
  // ...
});
